// TestSnap.idl : IDL source for TestSnap
//

// This file will be processed by the MIDL tool to
// produce the type library (TestSnap.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(613788ce-6e70-46fe-98b0-029f036c5757),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IATLSimpleObject : IDispatch
{
};
[
	uuid(1dd2b951-5f7f-4d70-81ba-fd460ebe9f07),
	version(1.0),
]
library TestSnapLib
{
	importlib("stdole2.tlb");
	[
		uuid(b9876b7d-e5f2-43a3-bf3e-94147a37bc2a)
	]
	coclass ATLSimpleObject
	{
		[default] interface IATLSimpleObject;
	};
};

import "shobjidl.idl";
