// MyATLProject.idl : IDL source for MyATLProject
//

// This file will be processed by the MIDL tool to
// produce the type library (MyATLProject.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
    uuid(6A3A67DD-1625-4637-B7DF-8E55719F88CC),  // Library UUID
        version(1.0)
]
library MyATLProjectLib
{
    importlib("stdole2.tlb");

    [
        uuid(06F0CFB7-7715-4886-B8F7-0B2FB4CF0C7A) // Interface UUID
    ]
        interface IMyComObject : IDispatch
    {
        HRESULT ShowMessage([in] BSTR message);
    };

    [
        uuid(E44E93DD-D430-42D8-831A-892B632D3115) // CLSID for CMyComObject
    ]
        coclass CMyComObject
    {
        [default] interface IMyComObject;
    };
};
